version: "3"
services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        links: [ consul ]
    consul:
        image: consul:1.12
